### ISSUE TITLE
Broken links on Code page

### ISSUE THREAD

**Issue by alcantarar** [m-clark/m-clark.github.io#1]
Hi,

There are broken links located on the Code web page of your (awesome) site. I tried the first couple of links in the Mixed Models section and got a github 404. 

Example:  
[https://github.com/m-clark/Miscellaneous-R-Code/blob/master/ModelFitting/onefactorRE.R](https://github.com/m-clark/Miscellaneous-R-Code/blob/master/ModelFitting/onefactorRE.R) sends user to github 404 by clicking on R code for "one factor random effects".

**Comment by m-clark** [comment]
Thanks for the heads up! I will take a look and fix.

**Comment by m-clark** [comment]
Should be fixed now!
