### ISSUE TITLE
code for replicating plots from online posts

### ISSUE THREAD

**Issue by statadvice** [m-clark/m-clark.github.io#4]
Thanks for amazing educational resources! However, there seems to be no code available for reproducing plots, such as those in this post:
https://m-clark.github.io/posts/2019-06-21-empirical-bayes/

**Comment by m-clark** [comment]
Hi @statadvice . I don't typically show this sort of thing in the final product, as it rarely helps to understand the content, adds to clutter, etc.  However the underlying code is always available in the repo itself ([for example](https://github.com/m-clark/m-clark.github.io/blob/master/_posts/2019-06-21-empirical-bayes/empirical-bayes.Rmd)).

**Comment by statadvice** [comment]
Thanks a lot. This is very helpful.
