### ISSUE TITLE
world_happiness.RData

### ISSUE THREAD

**Issue by tanthiamhuat** [m-clark/m-clark.github.io#6]
load('data/world_happiness.RData')
where can we find that world_happiness.RData? I look into 
https://github.com/m-clark/m-clark.github.io/tree/master/data
there is not any.

Thanks.

**Comment by m-clark** [comment]
Not sure what the specific reference is, but it likely is this here:

https://github.com/m-clark/noiris/blob/master/data/world_happiness.rda

**Comment by tanthiamhuat** [comment]
thanks.
________________________________
